In [2]:
import os
import sys 

import pandas as pd
import numpy as np
import random
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import matplotlib
import warnings
import pickle 
import stemflow

pd.set_option('display.max_columns', None)
# warnings.filterwarnings('ignore')

/Users/liyingnceas/anaconda3/envs/drnets/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
data = np.load('./data/fish/fish_data.npy', allow_pickle=True)
print("Data shape:", data.shape)

train_idx = np.load('./data/fish/fish_train_idx.npy')
test_idx = np.load('./data/fish/fish_test_idx.npy')

train_data = data[train_idx]
test_data=data[test_idx]
print(train_data)
#print(test_data)


Data shape: (61996, 58)
[[1. 1. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 1.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]]
